### ISSUE TITLE
Code running error

### ISSUE THREAD

**Issue by xjtupanda** [XuezheMax/flowseq#10]
Thanks for the inspiring work!
 When running the code I met a problem, maybe due to a version mismatch. I have to run in an environment with newer versions. Anyway, when I ran the `python -u distributed.py`, I bumped into the error:
```shell
Traceback (most recent call last):
  File "distributed.py", line 13, in <module>
    from flownmt.data import NMTDataSet
  File "/data/xjtupanda/experiments/audio_driven/head_motion/techs/flowseq-master/flownmt/__init__.py", line 1, in <module>
    from flownmt.flownmt import FlowNMT
  File "/data/xjtupanda/experiments/audio_driven/head_motion/techs/flowseq-master/flownmt/flownmt.py", line 11, in <module>
    from flownmt.modules import Encoder
  File "/data/xjtupanda/experiments/audio_driven/head_motion/techs/flowseq-master/flownmt/modules/__init__.py", line 1, in <module>
    from flownmt.modules.encoders import *
  File "/data/xjtupanda/experiments/audio_driven/head_motion/techs/flowseq-master/flownmt/modules/encoders/__init__.py", line 1, in <module>
    from flownmt.modules.encoders.encoder import Encoder
  File "/data/xjtupanda/experiments/audio_driven/head_motion/techs/flowseq-master/flownmt/modules/encoders/encoder.py", line 7, in <module>
    class Encoder(nn.Module):
  File "/data/xjtupanda/experiments/audio_driven/head_motion/techs/flowseq-master/flownmt/modules/encoders/encoder.py", line 25, in Encoder
    def forward(self, src_sents, masks=None) -> Tuple[torch.Tensor, torch.Tensor]:
  File "/data/xjtupanda/anaconda3/envs/gcn/lib/python3.7/site-packages/overrides/overrides.py", line 83, in overrides
    return _overrides(method, check_signature, check_at_runtime)
  File "/data/xjtupanda/anaconda3/envs/gcn/lib/python3.7/site-packages/overrides/overrides.py", line 170, in _overrides
    _validate_method(method, super_class, check_signature)
  File "/data/xjtupanda/anaconda3/envs/gcn/lib/python3.7/site-packages/overrides/overrides.py", line 189, in _validate_method
    ensure_signature_is_compatible(super_method, method, is_static)
  File "/data/xjtupanda/anaconda3/envs/gcn/lib/python3.7/site-packages/overrides/signature.py", line 102, in ensure_signature_is_compatible
    ensure_return_type_compatibility(super_type_hints, sub_type_hints, method_name)
  File "/data/xjtupanda/anaconda3/envs/gcn/lib/python3.7/site-packages/overrides/signature.py", line 303, in ensure_return_type_compatibility
    f"{method_name}: return type `{sub_return}` is not a `{super_return}`."
TypeError: Encoder.forward: return type `typing.Tuple[torch.Tensor, torch.Tensor]` is not a `<class 'NoneType'>`.

```

Seems like it's caused by the behavior of `@overrides` of package `overrides`, I have  no clue what this is doing, could you clarify this and make some modifications?
I'm runniing with Pytorh==1.10.1, Python==3.7.12, overrides==7.3.1. Thanks in advance.

**Comment by xjtupanda** [comment]
Commenting out the `@overrides` that raise the error is a temporary fix for me.

**Comment by XuezheMax** [comment]
Sorry for the late response. `@overrides` is a package to explicitly label the method overriding. I am not sure why this caused this error.

**Comment by xjtupanda** [comment]
@XuezheMax 
Thanks for your reply! I guess only the derived class should use the 'overrides' decorator since its method name, parameters, and return variables should be exactly the same as the parent class. I've fixed the problem following this rule.

By the way, is the graphical model for this an implicit one? I found this part a bit confusing. The latent variable sequence $\mathrm{z}$ has the same length as target sequence $\mathrm{y}$, but without temporal information or constraint like the Markov chain. Does the latent variable sequence has anything to do with temporal relationships? Or they're just encoding some information about input sequence $\mathrm{x}$ and does not necessarily correspond to the same time-step as in the target sequence? How should I understand this? Any illustration would be much appreciated.

**Comment by XuezheMax** [comment]
The latent z are not necesarily aligned with y. It contains contextual information from x, and learned via variational inference.
I am not sure what kind of illustration you need. Perhaps some tutorial on generative flow?

**Comment by xjtupanda** [comment]
> The latent z are not necesarily aligned with y. It contains contextual information from x, and learned via variational inference. I am not sure what kind of illustration you need. Perhaps some tutorial on generative flow?

Thanks so much for your time! I'm trying to adapt and extend the approach to a similar problem, and I might post some questions here if I meet some.

**Comment by violet-zct** [comment]
Yes, please feel free to post any of your questions here.

**Comment by xjtupanda** [comment]
I've re-implemented the method and used it in a seq2seq problem (regression of continuous variables instead of discrete word prediction). I like the idea of factorizing output prediction by introducing latent variables since this could bring a large speed boost, which motivates me to search for non-autoregressive solutions. However, from what I've observed from the experiment results, it's quite depressing since it could not match the results of a simple bi-LSTM or auto-regressive transformer; the prediction error is about twice as large. I'm wondering if it's because of the model tradeoff between accuracy and speed, so there is necessarily a gap, or if I should further tune the architecture and the hyper-parameters to catch up with them.

By the way, is the initialization step for the model necessary? I guess it's only necessary for the flow model part; the other initialization parts are just for sanity checks. The custom data loader is quite tricky and hard to manipulate, but it's hard for the official data loader by Pytorch to provide a single batch. If it's unnecessary, I might switch back to the official data loader provided by Pytorch.
